# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aimen Ben Aissa
email: aimenebenfika@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A london based photographer goes by the name of Aimen. Event and
  street photographer who takes photographs instead of snapshots.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
